// frontend/components/blood-type-card.tsx
import Card from "@mui/material/Card";
import CardContent from "@mui/material/CardContent";
import Typography from "@mui/material/Typography";
import { Box } from "@mui/material";

interface BloodTypeCardProps {
  type: string;
  canDonateTo: string[];
  canReceiveFrom: string[];
}

export default function BloodTypeCard({
  type,
  canDonateTo,
  canReceiveFrom,
}: BloodTypeCardProps) {
  return (
    <Card
      sx={{
        height: "100%",
        display: "flex",
        flexDirection: "column",
        transition: "transform 0.3s, box-shadow 0.3s",
        "&:hover": {
          transform: "translateY(-5px)",
          boxShadow: 6,
        },
      }}
    >
      <CardContent sx={{ flexGrow: 1 }}>
        <Typography
          variant="h4"
          component="div"
          gutterBottom
          align="center"
          color="primary"
          fontWeight="bold"
        >
          {type}
        </Typography>
        <Box sx={{ mb: 1.5 }}>
          <Typography variant="subtitle1" fontWeight="medium">
            Can donate to:
          </Typography>
          <Typography variant="body2" color="text.secondary">
            {canDonateTo.join(", ")}
          </Typography>
        </Box>
        <Box>
          <Typography variant="subtitle1" fontWeight="medium">
            Can receive from:
          </Typography>
          <Typography variant="body2" color="text.secondary">
            {canReceiveFrom.join(", ")}
          </Typography>
        </Box>
      </CardContent>
    </Card>
  );
}

// frontend-vue/src/components/BloodTypeCard.vue
<template>
  <v-card class="blood-card" elevation="2">
    <v-card-text class="flex-grow-1">
      <h2 class="text-center text-red-darken-4 font-weight-bold text-h4 mb-4">
        {{ type }}
      </h2>

      <div class="mb-3">
        <h4 class="text-subtitle-1 font-weight-medium mb-1">Can donate to:</h4>
        <p class="text-body-2 text-red-darken-4">
          {{ canDonateTo.join(', ') }}
        </p>
      </div>

      <div>
        <h4 class="text-subtitle-1 font-weight-medium mb-1">
          Can receive from:
        </h4>
        <p class="text-body-2 text-red-darken-4">
          {{ canReceiveFrom.join(', ') }}
        </p>
      </div>
    </v-card-text>
  </v-card>
</template>

<script setup>
defineProps({
  type: String,
  canDonateTo: Array,
  canReceiveFrom: Array,
});
</script>

<style scoped>
.blood-card {
  display: flex;
  flex-direction: column;
  transition: transform 0.3s ease, box-shadow 0.3s ease;
  height: 100%;
}
.blood-card:hover {
  transform: translateY(-5px);
  box-shadow: var(--v-shadow-6);
}
</style>
